### PR TITLE
Jitpack badge have trouble displaying latest version without some kin…

### PR DESCRIPTION
**Pull request by geiralund**
…d of semantic versioning. Add date and time before git sha, e.g. '1.2020.04.22-09.29.3fc81ee209e0'

### CODE REVIEW

**Comment by geiralund** [comment]
Maybe both releases (ie jitpack and GH-packages) should have same versioning ?

**Comment by androa** [comment]
An alternative inspired by ULID's way of doing monotonically increasing IDs: `date +%s | base32 | head -c 10` = `GE2TQNZVGQ`

**Comment by androa** [comment]
> Maybe both releases (ie jitpack and GH-packages) should have same versioning ?

That would be the best/easiest/most intuitive.

**Comment by geiralund** [comment]
```
Maybe both releases (ie jitpack and GH-packages) should have same versioning ?

That would be the best/easiest/most intuitive.
```

@davidsteinsland Will that cause any trouble?

**Comment by davidsteinsland** [comment]
is this just to fix a badge?

**Comment by androa** [comment]
Nja. It's also a bit tricky to understand what is the newest version (in Jitpack), without having to go to the releases page on GitHub.

**Pull request closed without merging**
